server:
  port: 10001
spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: demo
      password: #root
      username: #root
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    # 超时时间 Duration类型 6秒
    timeout: 6000
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 5

logging:
  config: classpath:logback-spring.xml
  path: D:/nmyslog/nmys